### ISSUE TITLE
Windows Defender

### ISSUE THREAD

**Issue by Komischerboy** [NYAN-x-CAT/AsyncRAT-C-Sharp#158] opened 2020-03-14 12:51 UTC
How can the Client bypass the Windows Defender?

**Comment by Komischerboy** [comment] 2020-03-15 12:51
idk why but now it bypass xd

**Comment by vungsung** [comment] 2020-03-26 04:28
Reminder: If the problem is solved please close the issue to let people focus on unsolved issues, thanks!

**Closed** 2020-03-28 08:43 UTC
